# Generated by Django 6.0.6 on 2026-07-03 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClashOfClan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('trophies', models.PositiveIntegerField(default=10)),
                ('town_hall_level', models.PositiveIntegerField(default=1)),
                ('war_stars', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Valorant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=100)),
                ('kd_ratio', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('rank_tier', models.CharField()),
                ('win_rate', models.FloatField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Valorant',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_handle', models.URLField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='pfp/')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer Not To Say', 'Prefer Not To Say')])),
                ('tier', models.CharField(choices=[('C-Tier', 'C-Tier'), ('B-Tier', 'B-Tier'), ('A-Tier', 'A-Tier'), ('S-Tier', 'S-Tier')], default='C-Tier')),
                ('clash_of_clans_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.clashofclan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('valorant_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.valorant')),
            ],
        ),
    ]
