# Generated by Django 6.0.6 on 2026-07-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='discord_handle',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='discord_username',
            field=models.CharField(default=''),
        ),
    ]
