# Generated by Django 6.0.6 on 2026-07-04 05:15

import django.db.models.deletion
import location_field.models.plain
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_userprofile_discord_handle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GamerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_username', models.CharField(default='')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='pfp/')),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer Not To Say', 'Prefer Not To Say')])),
                ('tier', models.CharField(choices=[('C-Tier', 'C-Tier'), ('B-Tier', 'B-Tier'), ('A-Tier', 'A-Tier'), ('S-Tier', 'S-Tier')], default='C-Tier')),
                ('clash_of_clans_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.clashofclan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamer_profile', to=settings.AUTH_USER_MODEL)),
                ('valorant_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.valorant')),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
