# Generated by Django 6.0.6 on 2026-07-04 05:33

import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_gamerprofile_recruiterprofile_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerprofile',
            name='profile_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gamerprofile',
            name='profile_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='26.470202829291104,80.2466219093185', max_length=63),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='profile_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='profile_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamerprofile',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='26.470202829291104,80.2466219093185', max_length=63),
        ),
    ]
