# Generated by Django 6.0.6 on 2026-07-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_gamerprofile_profile_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerprofile',
            name='profile_level',
        ),
        migrations.RemoveField(
            model_name='gamerprofile',
            name='profile_score',
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='event_credits',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
