# Generated by Django 6.0.6 on 2026-07-05 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_gamerprofile_profile_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecruiterProfile',
            new_name='HostProfile',
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('game', models.CharField(choices=[('Valorant', 'Valorant'), ('Free Fire', 'Free Fire'), ('BGMI', 'BGMI')], max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('live_at', models.DateTimeField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='app.hostprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to='app.gamerprofile')),
                ('player2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='second_player', to='app.gamerprofile')),
                ('player3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='third_player', to='app.gamerprofile')),
                ('player4', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fourth_player', to='app.gamerprofile')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tournament')),
            ],
        ),
    ]
